apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webui
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.14
          ports:
            - containerPort: 80
              protocol:  TCP
---
apiVersion: v1 
kind: Service
metadata: 
  name: clusterip-service
spec:
  type: ClusterIP
  clusterIP: 10.233.10.10
  selector:
    app: webui
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80